# Site settings
title: JUNYAN BAI
description: 'Project Portfolio for NOC Inbound'
url: 'https://www.zuehlke.cloud'
baseurl: ''
profilepic: '/images/portfolio.png'
bkimage: '/images/bk2.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'a0ef200358.js'

author:
  name: 'JUNYAN BAI'
  email: jbai0759@uni.sydney.edu.au
  # mastodon: tzuehlke@mstdn.social
  # twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  Wellshh
  # linkedin_username:  thomas-zühlke-889182165
  # meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
